# Generated by Django 3.2.6 on 2021-09-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatscooking', '0002_auto_20210910_0404'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=560)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=560)),
                ('music_releases', models.ManyToManyField(blank=True, to='whatscooking.MusicRelease')),
            ],
        ),
    ]
