# Generated by Django 3.2.6 on 2021-11-05 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatscooking', '0007_auto_20211105_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='default_recipe.png', upload_to='recipe_pics'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='serving_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
