# Generated by Django 3.2.6 on 2021-11-12 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('whatscooking', '0008_auto_20211105_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='created_by',
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
