# Generated by Django 3.2.6 on 2021-11-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatscooking', '0010_auto_20211112_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
