# Generated by Django 3.2.6 on 2021-11-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatscooking', '0011_alter_recipe_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeasurementQuantity',
        ),
        migrations.DeleteModel(
            name='MeasurementUnit',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='vegan',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='vegetarian',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, default='default_ingredient.png', upload_to='ingredient_pics'),
        ),
        migrations.DeleteModel(
            name='PantryIngredient',
        ),
    ]
