# Generated by Django 3.2.6 on 2021-11-12 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatscooking', '0012_auto_20211112_1957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
